- id: cs2_bridge_apply_tvled_state_on_change
  alias: CS2 Bridge - Apply TVLED State on Change
  trigger:
    - platform: state
      entity_id:
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
      id: hard_reset

    - platform: state
      entity_id:
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_smoked
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
      id: normal_refresh

  action:
    - choose:
        - conditions:
            - condition: trigger
              id: hard_reset
          sequence:
            - service: script.turn_off
              target:
                entity_id:
                  - script.cs2_bridge_restore_context_tvled
                  - script.cs2_bridge_low_hp_team_breath_tvled
                  - script.cs2_bridge_critical_hp_red_breath_tvled
                  - script.cs2_bridge_burning_flicker_tvled
            - delay:
                milliseconds: 150
            - service: light.turn_on
              target:
                entity_id: light.cozylife_8nqa_light_2
              data:
                brightness_pct: >
                  {% if states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase') == 'freezetime' %}
                    100
                  {% else %}
                    35
                  {% endif %}
                hs_color: >
                  {% if states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team') == 'CT' %}
                    [240, 100]
                  {% elif states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team') == 'T' %}
                    [120, 100]
                  {% else %}
                    [0, 0]
                  {% endif %}
            - service: script.turn_on
              target:
                entity_id: script.cs2_bridge_apply_tvled_state

      default:
        - service: script.turn_on
          target:
            entity_id: script.cs2_bridge_apply_tvled_state
  mode: restart

- id: cs2_bridge_bombtimer_einzig_tvled
  alias: CS2 Bridge - Bombtimer einzig TVLED
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_pulse
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
              above: 0
          sequence:
            - stop: Flash overlay aktiv

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
              state: "blink"
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
              state: "red"
            - condition: state
              entity_id: binary_sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_pulse
              state: "off"
          sequence:
            - service: script.turn_off
              target:
                entity_id:
                  - script.cs2_bridge_restore_context_tvled
                  - script.cs2_bridge_apply_tvled_state
                  - script.cs2_bridge_low_hp_team_breath_tvled
                  - script.cs2_bridge_critical_hp_red_breath_tvled
                  - script.cs2_bridge_burning_flicker_tvled
            - service: light.turn_on
              target:
                entity_id: light.cozylife_8nqa_light_2
              data:
                brightness_pct: 100
                rgb_color: [255, 0, 0]

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
              state: "blink"
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_color
              state: "red"
            - condition: state
              entity_id: binary_sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_pulse
              state: "on"
          sequence:
            - service: script.turn_off
              target:
                entity_id:
                  - script.cs2_bridge_restore_context_tvled
                  - script.cs2_bridge_apply_tvled_state
                  - script.cs2_bridge_low_hp_team_breath_tvled
                  - script.cs2_bridge_critical_hp_red_breath_tvled
                  - script.cs2_bridge_burning_flicker_tvled
            - service: light.turn_off
              target:
                entity_id: light.cozylife_8nqa_light_2

      default:
        - stop: Nicht im Bombtimer-Modus
  mode: restart

- id: cs2_bridge_bomb_exploded_rot_kurz_tvled
  alias: CS2 Bridge - Bomb exploded rot kurz TVLED
  trigger:
    - platform: state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
      to: "exploded"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_tvled
          - script.cs2_bridge_critical_hp_red_breath_tvled
          - script.cs2_bridge_burning_flicker_tvled
    - service: light.turn_on
      target:
        entity_id: light.cozylife_8nqa_light_2
      data:
        brightness_pct: 100
        rgb_color: [255, 0, 0]
    - delay:
        seconds: 5
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_tvled
  mode: restart

- id: cs2_bridge_bomb_defused_blau_blinken_tvled
  alias: CS2 Bridge - Bomb defused blau blinken TVLED
  trigger:
    - platform: state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
      to: "defused"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_tvled
          - script.cs2_bridge_critical_hp_red_breath_tvled
          - script.cs2_bridge_burning_flicker_tvled
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_defused_blue_blink_tvled
  mode: restart

- id: cs2_bridge_burning_start_tvled
  alias: CS2 Bridge - Burning Start TVLED
  trigger:
    - platform: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
      above: 0
  condition:
    - condition: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
      below: 1
    - condition: template
      value_template: "{{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode') | lower not in ['blink'] }}"
    - condition: template
      value_template: "{{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb') | lower not in ['defused', 'exploded'] }}"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_tvled
          - script.cs2_bridge_critical_hp_red_breath_tvled
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_burning_flicker_tvled
  mode: restart

- id: cs2_bridge_burning_ende_tvled
  alias: CS2 Bridge - Burning Ende TVLED
  trigger:
    - platform: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
      below: 1
  action:
    - service: script.turn_off
      target:
        entity_id: script.cs2_bridge_burning_flicker_tvled
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_tvled
  mode: restart

- id: cs2_bridge_flashed_kurzer_flash_tvled
  alias: CS2 Bridge - Flashed kurzer Flash TVLED
  trigger:
    - platform: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
      above: 0
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_tvled
          - script.cs2_bridge_critical_hp_red_breath_tvled
          - script.cs2_bridge_burning_flicker_tvled
          - script.cs2_bridge_restore_context_tvled
    - service: light.turn_on
      target:
        entity_id: light.cozylife_8nqa_light_2
      data:
        brightness_pct: 100
        color_temp_kelvin: 6500
    - delay:
        milliseconds: 1400
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
          below: 1
      timeout: "00:00:02"
      continue_on_timeout: true
    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_tvled
  mode: restart

- id: cs2_bridge_low_hp_controller_tvled
  alias: CS2 Bridge - Low HP Controller TVLED
  trigger:
    - platform: state
      entity_id:
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_smoked
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb
        - sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_phase
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_low_hp_team_breath_tvled
          - script.cs2_bridge_critical_hp_red_breath_tvled

    - choose:
        - conditions:
            - condition: template
              value_template: >
                {{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode') | lower in ['blink']
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb') | lower in ['exploded', 'defused']
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed') | float(0) > 0
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning') | float(0) > 0
                   or states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_smoked') | float(0) > 0 }}
          sequence:
            - stop: Higher priority active

        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              above: 0
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              below: 16
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.cs2_bridge_critical_hp_red_breath_tvled

        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              above: 15
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              below: 30
          sequence:
            - service: script.turn_on
              target:
                entity_id: script.cs2_bridge_low_hp_team_breath_tvled

      default:
        - service: script.turn_on
          target:
            entity_id: script.cs2_bridge_apply_tvled_state
  mode: restart

- id: cs2_bridge_damage_kurzer_boost_tvled
  alias: CS2 Bridge - Damage kurzer Boost TVLED
  trigger:
    - platform: state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state is not none
           and trigger.to_state is not none
           and trigger.from_state.state not in ['unknown','unavailable','none','None','']
           and trigger.to_state.state not in ['unknown','unavailable','none','None','']
           and (trigger.to_state.state | int(0)) < (trigger.from_state.state | int(0))
           and (trigger.to_state.state | int(0)) > 0 }}
    - condition: template
      value_template: "{{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_light_mode') | lower not in ['blink'] }}"
    - condition: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_flashed
      below: 1
    - condition: numeric_state
      entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_burning
      below: 1
    - condition: template
      value_template: "{{ states('sensor.cs2_gsi_bridge_cs2_gsi_bridge_round_bomb') | lower not in ['exploded', 'defused'] }}"
  action:
    - service: script.turn_off
      target:
        entity_id:
          - script.cs2_bridge_restore_context_tvled
          - script.cs2_bridge_low_hp_team_breath_tvled
          - script.cs2_bridge_critical_hp_red_breath_tvled

    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_state_health
              below: 16
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.cozylife_8nqa_light_2
              data:
                brightness_pct: 100
                hs_color: [0, 100]

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
              state: "CT"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.cozylife_8nqa_light_2
              data:
                brightness_pct: 100
                hs_color: [240, 100]

        - conditions:
            - condition: state
              entity_id: sensor.cs2_gsi_bridge_cs2_gsi_bridge_player_team
              state: "T"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.cozylife_8nqa_light_2
              data:
                brightness_pct: 100
                hs_color: [120, 100]

      default:
        - service: light.turn_on
          target:
            entity_id: light.cozylife_8nqa_light_2
          data:
            brightness_pct: 100
            color_temp_kelvin: 4500

    - delay:
        milliseconds: 500

    - service: script.turn_on
      target:
        entity_id: script.cs2_bridge_restore_context_tvled
  mode: restart
